module.exports = {
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",

  CREATE_PRODUCT: "CREATE_PRODUCT",
  UPDATE_PRODUCT: "UPDATE_PRODUCT",
  DELETE_PRODUCT: "DELETE_PRODUCT",

  CREATE_ORDER: "CREATE_ORDER",
  UPDATE_ORDER_STATUS: "UPDATE_ORDER_STATUS",
  CANCEL_ORDER: "CANCEL_ORDER",

  APPROVE_PROFILE_UPDATE: "APPROVE_PROFILE_UPDATE",
  REJECT_PROFILE_UPDATE: "REJECT_PROFILE_UPDATE",

  UPDATE_SELLER_COMMISSION: "UPDATE_SELLER_COMMISSION",

  CREATE_COUPON: "CREATE_COUPON",
  UPDATE_COUPON: "UPDATE_COUPON",

  ADMIN_LOGIN: "ADMIN_LOGIN",

  SYSTEM_EVENT: "SYSTEM_EVENT"
};
