module.exports = {
  OTP: process.env.SMS_TEMPLATE_OTP,
  // Using ORDER_CONFIRMED from .env for ORDER_PLACED event
  ORDER_PLACED: process.env.SMS_TEMPLATE_ORDER_CONFIRMED || process.env.SMS_TEMPLATE_ORDER_PLACED,
  ORDER_CONFIRMED: process.env.SMS_TEMPLATE_ORDER_CONFIRMED || process.env.SMS_TEMPLATE_ORDER_PLACED,
  ORDER_SHIPPED: process.env.SMS_TEMPLATE_ORDER_SHIPPED,
   ORDER_CANCELLED: process.env.SMS_TEMPLATE_ORDER_CANCELLED,
  OUT_FOR_DELIVERY: process.env.SMS_TEMPLATE_OUT_FOR_DELIVERY,
  DELIVERED: process.env.SMS_TEMPLATE_DELIVERED,
  RETURN_REQUEST: process.env.SMS_TEMPLATE_RETURN_REQUEST,
  RETURN_APPROVED: process.env.SMS_TEMPLATE_RETURN_APPROVED,
  RETURN_REJECTED: process.env.SMS_TEMPLATE_RETURN_REJECTED,
  REFUND_INITIATED: process.env.SMS_TEMPLATE_REFUND_INITIATED,
  REFUND_COMPLETED: process.env.SMS_TEMPLATE_REFUND_COMPLETED,
  PAYMENT_FAILED: process.env.SMS_TEMPLATE_PAYMENT_FAILED,
  // Renamed for consistency with smsTemplateStrings.js
  PASSWORD_RESET: process.env.SMS_TEMPLATE_PASSWORD_RESET_OTP || process.env.SMS_TEMPLATE_RESET_OTP,
  ACCOUNT_CREATED: process.env.SMS_TEMPLATE_ACCOUNT_CREATED,
};